"""规则层线索词表（codebook `config/codebook/frames_zh.md` 的可执行子集）。

诚实边界：本词表是 codebook 的 v0 近似，测量效度（ρ≥0.8 硬门禁）未通过前
产出的框架分布仅作内部开发用途，禁用于对外数字（裁决 B 措辞纪律）。
"""

from __future__ import annotations

from oh_contracts.enums import FrameLabel

FRAME_KEYWORDS: dict[FrameLabel, tuple[str, ...]] = {
    FrameLabel.LOSS: (
        "损失",
        "下跌",
        "衰退",
        "风险",
        "危机",
        "裁员",
        "亏损",
        "下滑",
        "恶化",
        "违约",
        "泡沫",
        "失业",
        "收紧",
        "萎缩",
        "暴跌",
        "受挫",
        "loss",
        "losses",
        "downturn",
        "recession",
        "risk",
        "risks",
        "crisis",
        "layoffs",
        "slump",
        "deteriorat",
        "default",
        "bubble",
        "unemployment",
        "contraction",
        "plunge",
        "selloff",
    ),
    FrameLabel.GAIN: (
        "增长",
        "复苏",
        "回升",
        "收益",
        "上涨",
        "改善",
        "机遇",
        "反弹",
        "提振",
        "扩张",
        "盈利",
        "好转",
        "走强",
        "乐观",
        "growth",
        "recover",
        "recovery",
        "rally",
        "gain",
        "gains",
        "improve",
        "improving",
        "opportunity",
        "rebound",
        "expansion",
        "profits",
        "upside",
        "robust",
        "optimis",
        "strengthens",
    ),
    FrameLabel.RESPONSIBILITY: (
        "责任",
        "归咎",
        "归因",
        "失职",
        "应对不力",
        "谴责",
        "问责",
        "失误",
        "政策错误",
        "管理不善",
        "blame",
        "blamed",
        "fault",
        "failure",
        "accountable",
        "mismanage",
        "criticized for",
        "attributed to",
        "owing to",
        "due to",
    ),
    FrameLabel.CONFLICT: (
        "争端",
        "制裁",
        "关税",
        "对抗",
        "谈判破裂",
        "分歧",
        "摩擦",
        "威胁",
        "报复",
        "禁令",
        "贸易战",
        "升级",
        "施压",
        "dispute",
        "sanction",
        "sanctions",
        "tariff",
        "tariffs",
        "confrontation",
        "friction",
        "threat",
        "retaliat",
        "trade war",
        "escalat",
        "crackdown",
        "restrictions",
    ),
    FrameLabel.HUMAN_INTEREST: (
        "家庭",
        "民众",
        "就业者",
        "小企业",
        "民生",
        "家庭生计",
        "工人",
        "储户",
        "退休",
        "普通人",
        "消费者",
        "families",
        "workers",
        "households",
        "ordinary people",
        "small businesses",
        "retirees",
        "savers",
        "consumers",
        "jobs",
    ),
    FrameLabel.OTHER: (),
}

STANCE_POSITIVE: tuple[str, ...] = (
    "支持",
    "称赞",
    "欢迎",
    "有效",
    "符合预期",
    "增强信心",
    "肯定",
    "乐观",
    "支持率",
    "support",
    "praise",
    "welcomed",
    "effective",
    "endorse",
    "in line with expectations",
    "boost confidence",
    "commend",
)

STANCE_NEGATIVE: tuple[str, ...] = (
    "批评",
    "失望",
    "质疑",
    "担忧",
    "谴责",
    "反对",
    "抨击",
    "抗议",
    "不满",
    "警告",
    "criticize",
    "criticism",
    "disappoint",
    "question",
    "concern",
    "oppose",
    "condemn",
    "slam",
    "protest",
    "warn",
)

# 框架线索词的文本窗口：stance 判定只在实体命中位置的邻域内计数
STANCE_WINDOW_CHARS = 80
# 主导框架最低置信：top_count/(top_count+2) 映射下 top_count=1 → 0.33，
# 低于此阈值不产行（弃权语义：无框架信号的文章不污染分布）
MIN_ROW_CONFIDENCE = 0.3
# confidence 保守映射分母：n 命中 → n/(n+K)，封顶 < 0.75（规则层不冒充高置信）
_CONF_MAP_K = 2
