"""OH!News 共享契约包。

架构约束（docs/BLUEPRINT.md §10）：
- 零内部依赖：禁止 import 任何 oh_* 业务包（CI purity 测试强制）。
- 零 IO：禁止 open()/pathlib/os 等（CI purity 测试强制）。
- 仅存放 Pydantic schema、StrEnum 枚举与常量。
"""

from oh_contracts.belief import (
    BeliefChangeType,
    BeliefCreate,
    BeliefSnapshot,
    BeliefStance,
    stance_zh,
)
from oh_contracts.briefing import (
    BriefingResponse,
    ChangeBrief,
    ChangeDossier,
    ChangeKind,
    CoverageSummary,
    DataFreshness,
    EvidenceBucket,
    EvidenceCitation,
    EvidenceGap,
    EvidenceSet,
    StalenessLevel,
    StrengthWord,
    SubjectRef,
    TechnicalAnnex,
)
from oh_contracts.change_landscape import (
    ChangeFieldPayload,
    ChangeFieldPoint,
    ChangeLandscape,
    NarrativeStream,
    QualifiedChange,
    QualityWarning,
    SourceStream,
    TimeWindow,
)
from oh_contracts.constants import (
    BOOTSTRAP_RESAMPLES,
    CONF_TAU_RULE,
    CONF_TAU_SMALL,
    JEFFREYS_ALPHA,
    N_MIN_SAMPLES,
    PIT_LOOKBACK_DAYS,
    PSI_ALERT_THRESHOLD,
    TYPE_FACTOR,
    VERIFY_BONUS_CORROBORATED,
    VERIFY_PENALTY_SINGLE,
    VERIFY_PENALTY_UNVERIFIED,
)
from oh_contracts.dissection import (
    ArticleDissection,
    DissectionElement,
    DissectionSpan,
    ElementKey,
)
from oh_contracts.enums import (
    ArticleType,
    ClaimKind,
    EpistemicStatus,
    ExtractionEngine,
    FrameLabel,
    SOStrategy,
    SourceTier,
    SSEEvent,
    StanceLabel,
    Tier,
)
from oh_contracts.icd203 import PROBABILITY_RANGES, ProbabilityTerm, term_for_probability
from oh_contracts.ids import content_hash, make_item_key, url_hash
from oh_contracts.intel import AchCell, AchMatrix, AchRow, IntelReport, KeyJudgment
from oh_contracts.intents import (
    AnalysisArtifact,
    ArtifactKind,
    ContextPacket,
    Intent,
    IntentKind,
    TargetKind,
)
from oh_contracts.narrative import (
    EventAssessment,
    EventStatus,
    EvidenceItem,
    EvidenceRole,
    EvidenceStrength,
    Insight,
    NarrativeMomentum,
    NarrativeStatement,
)
from oh_contracts.ranking import (
    WEIGHTS,
    entity_importance,
    impact_factor,
    intelligence_score,
    novelty_factor,
)
from oh_contracts.reports import AgentReport, ReportKind, ReportSection
from oh_contracts.schemas import (
    BronzeRecord,
    Claim,
    EventRecord,
    Evidence,
    Hypothesis,
    NarrativeCard,
    NDIPoint,
    SourceMeta,
    SSEMessage,
    StanceRow,
)
from oh_contracts.semantics import (
    ActionMention,
    EmotionLabel,
    EmotionVector,
    EntityEdge,
    SemanticAnnotation,
    SemanticRole,
)
from oh_contracts.signals import Signal, SignalKind
from oh_contracts.text import strip_html
from oh_contracts.watching import (
    WatchKind,
    WatchReview,
    WatchUpdate,
)

__all__ = [
    "AnalysisArtifact",
    "ArtifactKind",
    "ContextPacket",
    "Intent",
    "IntentKind",
    "QualifiedChange",
    "QualityWarning",
    "TargetKind",
    "strip_html",
    "BOOTSTRAP_RESAMPLES",
    "CONF_TAU_RULE",
    "CONF_TAU_SMALL",
    "JEFFREYS_ALPHA",
    "N_MIN_SAMPLES",
    "PIT_LOOKBACK_DAYS",
    "PSI_ALERT_THRESHOLD",
    "TimeWindow",
    "TYPE_FACTOR",
    "VERIFY_BONUS_CORROBORATED",
    "VERIFY_PENALTY_SINGLE",
    "VERIFY_PENALTY_UNVERIFIED",
    "ArticleType",
    "BronzeRecord",
    "stance_zh",
    "Claim",
    "ClaimKind",
    "EpistemicStatus",
    "EventRecord",
    "Evidence",
    "ExtractionEngine",
    "FrameLabel",
    "ArticleDissection",
    "AgentReport",
    "ReportKind",
    "ReportSection",
    "ChangeFieldPayload",
    "DissectionElement",
    "DissectionSpan",
    "DissectionEngine",
    "ElementKey",
    "ChangeFieldPoint",
    "ChangeLandscape",
    "Hypothesis",
    "NDIPoint",
    "PROBABILITY_RANGES",
    "ProbabilityTerm",
    "NarrativeCard",
    "NarrativeStream",
    "SOStrategy",
    "SSEEvent",
    "SSEMessage",
    "SourceMeta",
    "SourceStream",
    "SourceTier",
    "StanceLabel",
    "StanceRow",
    "Tier",
    "AchCell",
    "Signal",
    "SignalKind",
    "EventAssessment",
    "EventStatus",
    "EvidenceItem",
    "EvidenceRole",
    "EvidenceStrength",
    "Insight",
    "NarrativeMomentum",
    "NarrativeStatement",
    "WEIGHTS",
    "entity_importance",
    "impact_factor",
    "intelligence_score",
    "novelty_factor",
    "AchMatrix",
    "AchRow",
    "IntelReport",
    "KeyJudgment",
    "content_hash",
    "make_item_key",
    "term_for_probability",
    "url_hash",
    "ActionMention",
    "EmotionLabel",
    "EmotionVector",
    "EntityEdge",
    "SemanticAnnotation",
    "SemanticRole",
    "BeliefChangeType",
    "BeliefCreate",
    "BeliefSnapshot",
    "BeliefStance",
    "BriefingResponse",
    "ChangeBrief",
    "ChangeDossier",
    "ChangeKind",
    "CoverageSummary",
    "DataFreshness",
    "EvidenceBucket",
    "EvidenceCitation",
    "EvidenceGap",
    "EvidenceSet",
    "StalenessLevel",
    "StrengthWord",
    "SubjectRef",
    "TechnicalAnnex",
    "WatchKind",
    "WatchReview",
    "WatchUpdate",
]
